# Generated by Django 5.1.4 on 2024-12-18 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'meal')},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'meal'], name='api_rating_user_id_aee66a_idx'),
        ),
    ]
