# Generated by Django 5.1.4 on 2024-12-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='api_rating_user_id_aee66a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
